<?php

return [
    'error_required' => ' is required.',
    'error_min' => [" must be minimum of ", " characters."],
    'error_max' => [" must be maximum of ", " characters."],
    'error_unique' => " alredy exists.",
    'error_unique_update' => " alredy exists.",
    'error_matches' => ["Fields ", " and ", " must match."],
    'error_valid_email' => ' must be a valid email address.',
    'error_filesize' => ['File size greater than ', ' Mb.'],
    'error_filetype' => 'Invalid file type.',
    'valid_required' => 'Please fill out this field.',
    'name_page' => 'Registration',
    'required' => 'is required.',
    'user_login' => 'Nickname',
    'email' => 'E-mail',
    'email_help' => 'We\'ll never share your email with anyone else.',
    'user_password' => 'Password',
    'password_help' => 'Must be 6-40 characters long.',
    'confirm' => 'Confirm password',
    'button_register' => 'Register',
    'user_name' => 'Full name',
    'user_birthday' => 'Birthday',
    'user_photo' => 'Photo',
    'help_user_photo1' => 'File type must be .jpg, .jpeg, .png or .gif.',
    'help_user_photo2' => 'File size must be less than 2 Mb.',
    'user_text_photo' => 'Upload Photo',
    'browse' => 'Browse',
    'about_myself' => 'About myself',
];